import type { SpeechSettingsInfo } from '../api/client';
export function speechFixture(state: 'ready' | 'download' | 'downloading' | 'error' | 'setup' = 'ready'): SpeechSettingsInfo {
  return {revision: 'fixture1', active: {stt: 'grok:stt', tts: 'grok:tts'}, downloads: state === 'downloading' ? [{name:'whisper-base',label:'Whisper base',state:'downloading',done_bytes:0,total_bytes:0,detail:''},{name:'kokoro-v1.0.onnx',label:'Kokoro voice model',state:'downloading',done_bytes:136_000_000,total_bytes:326_000_000,detail:''}] : [], engines: [
    {id:'grok:stt',provider:'grok',setup_action:'system-settings',direction:'stt',label:'Grok',location:'Online',model:'',live:true,description:'Supports live transcription.',languages:'Multilingual',state:'ready',detail:'Try a sample before switching.',voices:[],bindings:{}},
    {id:'grok:tts',provider:'grok',setup_action:'system-settings',direction:'tts',label:'Grok',location:'Online',model:'',live:true,description:'Supports streamed replies.',languages:'Multilingual',state:'ready',detail:'Your current voices are available.',voices:[{id:'lux',label:'Lux'},{id:'rex',label:'Rex'},{id:'luna',label:'Luna'}],bindings:{lux:'lux',rex:'rex',luna:'luna'}},
    ...['base','small','medium','large-v3','tiny'].map(model => ({id:`whisper:${model}`,provider:'local',direction:'stt' as const,label:`Whisper ${model}`,location:'On this Mac',model,live:false,description: ({base:'Compact · lower memory use',small:'Larger · more recognition capacity',medium:'Large · more memory and processing', 'large-v3':'Largest · try on this Mac before choosing',tiny:'Smallest · quick experiments'} as Record<string,string>)[model]!,languages:'Multilingual',state,detail:state==='ready'?'Model files are on this Mac.':state==='setup'?'This installation is missing offline speech support. Use a desktop build with offline support, or keep your current engine.':state==='error'?'The download did not finish. Retry when your connection is available.':'Download once, then use offline.',voices:[],bindings:{}})),
    {id:'kokoro:1',provider:'local',direction:'tts',label:'Kokoro',location:'On this Mac',model:'kokoro',live:false,description:'The full reply is generated before playback.',languages:'English voices in this integration',state,detail:state==='setup'?'This installation is missing offline speech support. Use a desktop build with offline support, or keep your current engine.':'Your current engine stays active until you apply.',voices:[{id:'af_sarah',label:'Sarah · US'},{id:'am_adam',label:'Adam · US'},{id:'bf_emma',label:'Emma · UK'}],bindings:{lux:'af_sarah',rex:'am_adam',luna:'bf_emma'}},
  ]};
}
