#!/usr/bin/env python3
"""Copy canonical desktop artwork and generate exact portrait frames; no image edits."""
import json
from pathlib import Path
import shutil
import subprocess
dart = shutil.which('dart')
if dart is None:
    raise SystemExit('Add the Flutter SDK bin directory to PATH before syncing desktop design.')
root = Path(__file__).resolve().parents[2]
source = root / 'dashboard/src'
target = root / 'mobile'
assets = target / 'assets/avatars'
assets.mkdir(parents=True, exist_ok=True)
for name in ['portrait-frames.json', 'crop-metadata.json', 'voice-order.json']:
    shutil.copyfile(source / 'avatars' / name, assets / name)
shutil.copyfile(source / 'assets/voice-avatars/editorial.webp', assets / 'editorial.webp')
voices = json.loads((assets / 'voice-order.json').read_text())
frames = json.loads((assets / 'portrait-frames.json').read_text())['editorial']
crop = json.loads((assets / 'crop-metadata.json').read_text())['editorial']
code = ["// Generated by scripts/sync_desktop_design.py from desktop avatar catalog.", "// Keep irregular crop geometry: uniform grid cropping regresses issue #160.", "import 'dart:ui';", f"const portraitSheetSize = Size({crop['width']}, {crop['height']});", "const portraitFrames = <String, Rect>{"]
for voice, frame in zip(voices, frames, strict=True):
    code.append(f"  '{voice}': Rect.fromLTWH({frame['left']}, {frame['top']}, {frame['width']}, {frame['height']}),")
code.append('};\n')
(target / 'lib/ui/avatar_catalog.dart').write_text('\n'.join(code))

# The daemon sends descriptive suffixes. Preserve desktop prefix precedence.
import re
machine = (source / 'machines/chat.ts').read_text()
chips = (source / 'components/bubbleStatus.ts').read_text()
status_code = ["// Generated from desktop machines/chat.ts and components/bubbleStatus.ts."]
for role, table in [('user', 'USER'), ('agent', 'CLAUDE')]:
    block = re.search(rf'const {table}_STATUS_PREFIXES.*?= \[(.*?)\n\];', machine, re.S).group(1)
    pairs = re.findall(r'\["([^"]+)", "([^"]+)"\]', block)
    status_code.append(f'const {role}StatusPrefixes = <(String, String)>[')
    status_code.extend(f'  ({json.dumps(prefix)}, {json.dumps(state)}),' for prefix, state in pairs)
    status_code.append('];')
    block = re.search(rf'const {table}_CHIPS.*?= \{{(.*?)\n\}};', chips, re.S).group(1)
    states = re.findall(r'(\w+): \{ kind: "([^"]+)", label: "([^"]+)" \}', block)
    status_code.append(f'const {role}StatusChips = <String, (String, String)>{{')
    status_code.extend(f'  "{state}": ({json.dumps(kind)}, {json.dumps(label, ensure_ascii=False)}),' for state, kind, label in states)
    status_code.append('};')
status_code.append('''
String? messageState(String role, String status) {
  final prefixes = role == 'user' ? userStatusPrefixes : agentStatusPrefixes;
  for (final entry in prefixes) {
    if (status.toLowerCase().startsWith(entry.$1)) return entry.$2;
  }
  return null;
}
(String, String) messageChip(String role, String status) {
  final chips = role == 'user' ? userStatusChips : agentStatusChips;
  return chips[messageState(role, status)] ?? ('work', status.toUpperCase());
}
''')
(target / 'lib/ui/message_status.dart').write_text('\n'.join(status_code))

subprocess.run([dart, 'format', str(target / 'lib/ui/avatar_catalog.dart'), str(target / 'lib/ui/message_status.dart')], check=True)
