<script setup lang="ts">
import { computed } from 'vue';
import CompanyPortrait from './CompanyPortrait.vue';
import type { CompanyDepartment } from './cast';
const props = withDefaults(defineProps<{ departments: CompanyDepartment[]; variant?: 'heads' | 'caption' | 'constellation'; speaking?: string }>(), { variant: 'heads', speaking: 'design-1' });
const people = computed(() => props.departments.flatMap(d => [d.lead, ...d.workers]));
const speaker = computed(() => people.value.find(p => p.id === props.speaking));
const working = computed(() => people.value.filter(p => p.working || p.id === props.speaking).length);
</script>
<template>
<section class="crew-stage" :class="`crew-${variant}`" aria-label="Flat crew Stage design preview">
  <header><div class="brand"><b>n<span>·</span></b><div><strong>Stage</strong><small>A little room for a bigger crew</small></div></div><span class="preview-label">FICTIONAL CREW · DESIGN LAB</span></header>
  <div class="room-caption"><span/>{{ speaker ? `${speaker.name} is speaking` : 'Room to think out loud' }}</div>
  <main class="crew" aria-label="Department leads and their specialists">
    <section v-for="d in departments" :key="d.id" class="department" :aria-label="d.name" :style="{ '--accent': d.color }">
      <CompanyPortrait :person="d.lead" :size="120" :speaking="speaking === d.lead.id"/>
      <h2>{{ d.name }}</h2>
      <div class="workers"><CompanyPortrait v-for="person in d.workers" :key="person.id" :person="person" :size="57" :speaking="speaking === person.id" specialist/></div>
    </section>
  </main>
  <div v-if="variant === 'caption'" class="caption"><span>{{ speaker?.name ?? 'THE CREW' }} <small>· SAMPLE CAPTION</small></span><p>“Good news: we have a plan. Better news: the team has opinions.”</p></div>
  <footer><span class="crew-size">{{ people.length }} voices <small>ONE CREW</small></span><div class="legend"><span><b>●</b> {{ working }} working</span><span><b>○</b> {{ people.length - working }} idle</span></div><p>Different minds. Same room.</p></footer>
</section>
</template>
<style scoped>
.crew-stage{box-sizing:border-box;min-height:100dvh;padding:28px 38px 24px;background:radial-gradient(ellipse at 49% 44%,#1c3533 0%,#132624 38%,#0b1719 76%);color:#eae6dc;font-family:var(--sans,system-ui,sans-serif);display:flex;flex-direction:column;position:relative;isolation:isolate}.crew-stage::before{content:'';position:absolute;inset:0;z-index:-1;opacity:.16;background-image:radial-gradient(#89afa0 .6px,transparent .6px);background-size:24px 24px;mask-image:radial-gradient(ellipse,#000,transparent 75%)}header{display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:center;gap:17px}.brand>b{font-size:38px;line-height:1}.brand>b span{color:#b6e3af}.brand strong{display:block;font-size:22px;font-weight:550;letter-spacing:-.7px}.brand small{display:block;margin-top:4px;font-size:12px;color:#9caaa5}.preview-label{font-size:9px;letter-spacing:1.4px;color:#8d9f96}.room-caption{display:flex;align-items:center;justify-content:center;gap:9px;color:#b0c0b5;font-size:11px;letter-spacing:.8px;margin-top:42px}.room-caption>span{width:5px;height:5px;border-radius:50%;background:#c6dfaf}.crew{flex:1;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));align-content:center;gap:26px;padding:35px 0 40px;max-width:1360px;width:100%;margin:auto}.department{min-width:0;text-align:center}.department h2{font-size:10px;font-weight:450;letter-spacing:1.2px;text-transform:uppercase;color:var(--accent);margin:20px 0 27px}.workers{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.workers :deep(.portrait:nth-child(2)){padding-top:18px}.crew-constellation .department:nth-child(2n){padding-top:85px}.crew-constellation .department:nth-child(2n + 1){padding-bottom:85px}.crew-constellation .crew{gap:38px;padding-top:18px;padding-bottom:20px}.crew-constellation .workers :deep(.portrait:first-child){padding-top:14px}.crew-constellation .workers :deep(.portrait:nth-child(2)){padding-top:0}.crew-constellation .workers :deep(.portrait:last-child){padding-top:21px}.caption{align-self:center;text-align:center;max-width:770px;border:1px solid #a1baa32b;border-radius:16px;background:#07151388;padding:15px 27px;margin:0 0 25px}.caption>span{font-size:11px;color:#bdda9b}.caption small{font-size:8px;color:#9eafa0;letter-spacing:.8px}.caption p{font-family:Georgia,serif;font-size:21px;line-height:1.4;margin:7px 0 0}footer{display:flex;align-items:center;justify-content:space-between;gap:25px;border-top:1px solid #acc5b41a;padding-top:20px}.crew-size{font-size:15px;color:#d1dac9}.crew-size small{font-size:8px;letter-spacing:1.5px;margin-left:9px;color:#9aae9e}.legend{display:flex;gap:22px;font-size:11px;color:#adbaac}.legend b{color:#c9e6ae;font-weight:400;margin-right:6px}.legend>span:last-child b{color:#9aa69d}footer p{font-size:11px;color:#9aada0;margin:0}
@media(min-width:1100px) and (max-height:800px){.crew-stage{padding-top:23px;padding-bottom:20px}.room-caption{margin-top:25px}.crew{padding-top:28px;padding-bottom:28px}.department>.portrait :deep(.voice-avatar){width:108px!important;height:108px!important}.department h2{margin:15px 0 20px}.caption{padding:12px 23px;margin-bottom:18px}.caption p{font-size:19px}.crew-constellation .department:nth-child(2n){padding-top:45px}.crew-constellation .department:nth-child(2n + 1){padding-bottom:45px}}
@media(max-width:1099px){.crew-stage{padding:25px}.crew{grid-template-columns:repeat(2,minmax(0,1fr));gap:48px 50px;padding-top:40px}.department h2{margin:16px 0 20px}.workers{max-width:280px;margin:auto}.crew-constellation .department:nth-child(n){padding:0}.crew-constellation .crew{padding-top:40px;gap:48px 50px}.preview-label{font-size:8px}}
@media(max-width:560px){.crew-stage{padding:20px 15px}.brand small{font-size:10px}.preview-label{display:none}.crew,.crew-constellation .crew{gap:45px 12px}.department>.portrait :deep(.voice-avatar){width:86px!important;height:86px!important}.workers{gap:2px}.workers :deep(.voice-avatar){width:37px!important;height:37px!important}.workers :deep(.frame){padding:3px}.workers :deep(.portrait strong){font-size:10px}.workers :deep(.role){font-size:8px}.workers :deep(.status){font-size:8px}.department h2{font-size:9px}.caption{padding:12px 16px}.caption p{font-size:17px}footer{gap:15px;flex-wrap:wrap}.legend{gap:14px}footer p{display:none}.crew-size small{display:none}}
</style>
