// Generated by scripts/sync_desktop_design.py from desktop avatar catalog.
// Keep irregular crop geometry: uniform grid cropping regresses issue #160.
import 'dart:ui';

const portraitSheetSize = Size(1374, 1145);
const portraitFrames = <String, Rect>{
  'altair': Rect.fromLTWH(0, 0, 230, 222),
  'ara': Rect.fromLTWH(230, 0, 228, 222),
  'atlas': Rect.fromLTWH(458, 0, 229, 222),
  'carina': Rect.fromLTWH(687, 0, 229, 222),
  'castor': Rect.fromLTWH(916, 0, 228, 222),
  'celeste': Rect.fromLTWH(1144, 0, 230, 222),
  'cosmo': Rect.fromLTWH(0, 227, 230, 214),
  'eve': Rect.fromLTWH(230, 227, 228, 214),
  'helios': Rect.fromLTWH(458, 227, 229, 214),
  'helix': Rect.fromLTWH(687, 227, 229, 214),
  'iris': Rect.fromLTWH(916, 227, 228, 214),
  'kepler': Rect.fromLTWH(1144, 227, 230, 214),
  'leo': Rect.fromLTWH(0, 446, 229, 216),
  'lumen': Rect.fromLTWH(229, 446, 229, 216),
  'luna': Rect.fromLTWH(458, 446, 228, 216),
  'lux': Rect.fromLTWH(686, 446, 230, 215),
  'naksh': Rect.fromLTWH(916, 446, 228, 216),
  'orion': Rect.fromLTWH(1144, 446, 230, 215),
  'perseus': Rect.fromLTWH(0, 662, 229, 219),
  'rex': Rect.fromLTWH(229, 662, 229, 219),
  'rigel': Rect.fromLTWH(458, 662, 229, 219),
  'sal': Rect.fromLTWH(687, 662, 229, 219),
  'sirius': Rect.fromLTWH(916, 662, 228, 219),
  'ursa': Rect.fromLTWH(1144, 662, 230, 219),
  'zagan': Rect.fromLTWH(0, 881, 229, 235),
  'zenith': Rect.fromLTWH(229, 881, 229, 235),
  'aurora': Rect.fromLTWH(458, 881, 228, 235),
  'liora': Rect.fromLTWH(686, 881, 236, 235),
};
